In [64]:
#import numpy to use seed 
import numpy as np
import pandas as pd
from numpy.random import seed
np.random.seed(1)

In [65]:
#import other dependencies

import os
import tensorflow 
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense

Read CSV create, and clean dataframe

In [66]:
#Read in CSV and create dataframe
mlb_teams= pd.read_csv("Teams.csv")

mlb_teams

,yearID,lgID,G,G.1,W,L,WSWin,R,AB,H,...,3B,HR,BB,SO,SB,ERA,CG,SHO,SV,name
0,2014,NL,162,81,64,98,N,615,5552,1379,...,47,118,398,1165,86,4.26,2,4,35,Arizona Diamondbacks
1,2014,NL,162,81,79,83,N,573,5468,1316,...,22,123,472,1369,95,3.38,5,13,54,Atlanta Braves
2,2014,AL,162,81,96,66,N,705,5596,1434,...,16,211,401,1285,44,3.43,3,13,53,Baltimore Orioles
3,2014,AL,162,81,71,91,N,634,5551,1355,...,20,123,535,1337,63,4.01,3,7,36,Boston Red Sox
4,2014,NL,162,81,73,89,N,614,5508,1315,...,31,157,442,1477,65,3.91,1,11,37,Chicago Cubs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,1969,NL,162,81,88,74,N,725,5626,1557,...,52,119,454,944,74,3.61,39,9,33,Pittsburgh Pirates
1225,1969,NL,162,81,52,110,N,468,5357,1203,...,42,99,423,1143,45,4.24,16,9,25,San Diego Padres
1226,1969,NL,162,81,90,72,N,713,5474,1325,...,28,136,711,1054,71,3.26,71,15,17,San Francisco Giants
1227,1969,NL,162,80,87,75,N,595,5536,1403,...,44,90,503,876,87,2.94,63,12,26,St. Louis Cardinals
1228,1969,AL,162,81,86,76,N,694,5447,1365,...,40,148,630,900,52,3.49,28,10,41,Washington Senators

In [67]:
#Get list of dataframe columns

mlb_teams.columns

Index(['yearID', 'lgID', 'G', 'G.1', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name'],
      dtype='object')

In [68]:
#Select columns for dataframe

mlb_df = mlb_teams[['yearID', 'lgID', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name']]
mlb_df.head(20)

,yearID,lgID,W,L,WSWin,R,AB,H,2B,3B,HR,BB,SO,SB,ERA,CG,SHO,SV,name
0,2014,NL,64,98,N,615,5552,1379,259,47,118,398,1165,86,4.26,2,4,35,Arizona Diamondbacks
1,2014,NL,79,83,N,573,5468,1316,240,22,123,472,1369,95,3.38,5,13,54,Atlanta Braves
2,2014,AL,96,66,N,705,5596,1434,264,16,211,401,1285,44,3.43,3,13,53,Baltimore Orioles
3,2014,AL,71,91,N,634,5551,1355,282,20,123,535,1337,63,4.01,3,7,36,Boston Red Sox
4,2014,NL,73,89,N,614,5508,1315,270,31,157,442,1477,65,3.91,1,11,37,Chicago Cubs
5,2014,AL,73,89,N,660,5543,1400,279,32,155,417,1362,85,4.29,3,6,36,Chicago White Sox
6,2014,NL,76,86,N,595,5395,1282,254,20,131,415,1252,122,3.59,5,13,44,Cincinnati Reds
7,2014,AL,85,77,N,669,5575,1411,284,23,142,504,1189,104,3.56,6,15,40,Cleveland Indians
8,2014,NL,66,96,N,755,5612,1551,307,41,186,397,1281,85,4.84,1,4,24,Colorado Rockies
9,2014,AL,90,72,N,757,5630,1557,325,26,155,443,1144,106,4.01,5,8,41,Detroit Tigers
10,2014,AL,70,92,N,629,5447,1317,240,19,163,495,1442,122,4.11,7,3,31,Houston Astros
11,2014,AL,89,73,N,651,5545,1456,286,29,95,380,985,153,3.51,3,14,53,Kansas City Royals
12,2014,AL,98,64,N,773,5652,1464,304,31,155,492,1266,81,3.58,3,13,46,Los Angeles Angels of Anaheim
13,2014,NL,94,68,N,718,5560,1476,302,38,134,519,1246,138,3.40,7,16,47,Los Angeles Dodgers
14,2014,NL,77,85,N,645,5538,1399,254,36,122,501,1419,58,3.78,3,16,42,Miami Marlins
15,2014,NL,82,80,N,650,5462,1366,297,28,150,423,1197,102,3.67,3,9,45,Milwaukee Brewers
16,2014,AL,70,92,N,715,5567,1412,316,27,128,544,1329,99,4.57,2,7,38,Minnesota Twins
17,2014,NL,79,83,N,629,5472,1306,275,19,125,516,1264,101,3.49,1,11,42,New York Mets
18,2014,AL,84,78,N,633,5497,1349,247,26,147,452,1133,112,3.75,5,10,48,New York Yankees
19,2014,AL,88,74,N,729,5545,1354,253,33,146,586,1104,83,3.22,7,13,31,Oakland Athletics

In [69]:
#Use getdummies to convert strings

data_LG = mlb_df.copy()
data_bin = pd.get_dummies(data_LG, columns=["WSWin", "lgID"])
data_bin = data_bin.drop(columns=['WSWin_N', 'lgID_AL'])

data_bin.head()

,yearID,W,L,R,AB,H,2B,3B,HR,BB,SO,SB,ERA,CG,SHO,SV,name,WSWin_Y,lgID_NL
0,2014,64,98,615,5552,1379,259,47,118,398,1165,86,4.26,2,4,35,Arizona Diamondbacks,0,1
1,2014,79,83,573,5468,1316,240,22,123,472,1369,95,3.38,5,13,54,Atlanta Braves,0,1
2,2014,96,66,705,5596,1434,264,16,211,401,1285,44,3.43,3,13,53,Baltimore Orioles,0,0
3,2014,71,91,634,5551,1355,282,20,123,535,1337,63,4.01,3,7,36,Boston Red Sox,0,0
4,2014,73,89,614,5508,1315,270,31,157,442,1477,65,3.91,1,11,37,Chicago Cubs,0,1

In [70]:
data = data_bin.drop("name", axis = 1)
outcome = data_bin["name"]
print(data.shape, outcome.shape)

(1229, 18) (1229,)

Preprocess data

In [71]:
#Import SciKit libraries

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from tensorflow.keras.utils import to_categorical

In [72]:
#Split data and teams into training and test data

X_train, X_test, y_train, y_test = train_test_split(data, outcome, random_state=1)
y_train

503        San Diego Padres
842       Milwaukee Brewers
419       Toronto Blue Jays
493      Kansas City Royals
325        Seattle Mariners
               ...
715           New York Mets
905     St. Louis Cardinals
1096     Kansas City Royals
235     St. Louis Cardinals
1061          Texas Rangers
Name: name, Length: 921, dtype: object

In [73]:
#Scale data using MinMaxScaler

X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_train_scaled

array([[ 0.42165868,  1.48268161, -1.32886979, ...,  2.29677766,
        -0.18663189,  1.0342451 ],
       [-0.63077397, -1.08243035,  1.18235874, ...,  0.36780557,
        -0.18663189, -0.9668888 ],
       [ 0.64717997, -0.00673824,  0.17786733, ...,  0.36780557,
        -0.18663189, -0.9668888 ],
       ...,
       [-1.38251158, -0.25497488,  0.42899018, ..., -2.20415721,
        -0.18663189, -0.9668888 ],
       [ 1.09822253, -0.17222933,  0.34528256, ..., -0.38235024,
        -0.18663189,  1.0342451 ],
       [-1.23216405, -0.33772042,  0.5126978 , ..., -2.41848744,
        -0.18663189, -0.9668888 ]])

In [74]:
#Import and use SVC MODEL
from sklearn.svm import SVC 
model = SVC(kernel='linear')
model.fit(X_train_scaled, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [75]:
#Print training and test scores from model using datasets

print(f"Training Data Score: {model.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {model.score(X_test_scaled, y_test)}")

Training Data Score: 0.47014115092290987
Testing Data Score: 0.29545454545454547

In [76]:
# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [100, 500, 1000],
              'gamma': [0.0001, 0.005, 0.001]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [77]:
# Train the model with GridSearch

grid.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] C=100, gamma=0.0001 .............................................

C:\Users\swill\Anaconda3\envs\PythonData\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] ................. C=100, gamma=0.0001, score=0.189, total=   2.3s
[CV] C=100, gamma=0.0001 .............................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.2s remaining:    0.0s

[CV] ................. C=100, gamma=0.0001, score=0.223, total=   1.8s
[CV] C=100, gamma=0.0001 .............................................

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    4.0s remaining:    0.0s

[CV] ................. C=100, gamma=0.0001, score=0.196, total=   1.7s
[CV] C=100, gamma=0.0001 .............................................
[CV] ................. C=100, gamma=0.0001, score=0.168, total=   2.1s
[CV] C=100, gamma=0.0001 .............................................
[CV] ................. C=100, gamma=0.0001, score=0.190, total=   2.3s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.189, total=   2.7s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.223, total=   2.0s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.196, total=   1.7s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.168, total=   2.1s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.190, total=   2.2s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.189, total=   2.6s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.223, total=   2.1s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.196, total=   1.9s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.168, total=   2.1s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.190, total=   2.0s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.200, total=   8.3s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.217, total=   7.7s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.212, total=   6.2s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.147, total=   8.4s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.207, total=   9.3s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.200, total=  11.7s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.217, total=   8.9s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.212, total=   7.1s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.147, total=   8.3s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.207, total=   9.0s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.200, total=   8.9s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.217, total=   8.1s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.212, total=   7.0s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.147, total=   9.3s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.207, total=  10.2s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.200, total=  17.5s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.228, total=  18.9s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.217, total=  18.9s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.147, total=  22.7s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.196, total=  16.4s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.200, total=  19.6s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.228, total=  17.4s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.217, total=  18.4s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.147, total=  19.1s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.196, total=  16.6s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.200, total=  17.3s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.228, total=  15.5s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.217, total=  15.3s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.147, total=  19.3s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.196, total=  16.9s

[Parallel(n_jobs=1)]: Done  45 out of  45 | elapsed:  7.2min finished

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [100, 500, 1000],
                         'gamma': [0.0001, 0.005, 0.001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

Train Model

In [78]:
#Print best parameters and score from Gridsearch

print(grid.best_params_)
print(grid.best_score_)

{'C': 1000, 'gamma': 0.0001}
0.1976086956521739

In [79]:
#Print accuracy of model using test dataset

print('Test Acc: %.3f' % grid.score(X_test_scaled, y_test))

Test Acc: 0.244

In [80]:
#Read in CSV and create dataframe
mlb_teams2015= pd.read_csv("2015.csv")

mlb2015_df = mlb_teams2015[['yearID', 'lgID', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name']]

data2015_LG = mlb2015_df.copy()
data2015_bin = pd.get_dummies(data2015_LG, columns=["WSWin", "lgID"])
data2015_bin = data2015_bin.drop(columns=['WSWin_N', 'lgID_AL'])

feature2015 = data2015_bin.drop("name", axis=1)
team2015 = data2015_bin["name"]

X_feature2015_scaler = StandardScaler().fit(feature2015)
X_feature2015_scaled = X_feature2015_scaler.transform(feature2015)

predictions2015 = grid.predict(X_feature2015_scaled)
print('Test Acc: %.3f' % grid.score(X_feature2015_scaled, team2015))
predictions2015 = model.predict(X_feature2015_scaled)
print(predictions2015)

Test Acc: 0.133
['St. Louis Cardinals' 'San Diego Padres' 'Detroit Tigers'
 'Minnesota Twins' 'Cincinnati Reds' 'Minnesota Twins' 'Cincinnati Reds'
 'Boston Red Sox' 'Colorado Rockies' 'Kansas City Royals'
 'Oakland Athletics' 'Kansas City Royals' 'Chicago White Sox'
 'Atlanta Braves' 'Los Angeles Dodgers' 'Pittsburgh Pirates'
 'Kansas City Royals' 'New York Mets' 'Baltimore Orioles'
 'Toronto Blue Jays' 'Pittsburgh Pirates' 'Houston Astros'
 'San Francisco Giants' 'St. Louis Cardinals' 'Baltimore Orioles'
 'San Francisco Giants' 'Seattle Mariners' 'Texas Rangers'
 'Oakland Athletics' 'New York Mets']

In [81]:
#Read in CSV and create dataframe
mlb_teams2016= pd.read_csv("2016.csv")

mlb2016_df = mlb_teams2016[['yearID', 'lgID', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name']]

data2016_LG = mlb2016_df.copy()
data2016_bin = pd.get_dummies(data2016_LG, columns=["WSWin", "lgID"])
data2016_bin = data2016_bin.drop(columns=['WSWin_N', 'lgID_AL'])

feature2016 = data2016_bin.drop("name", axis=1)
team2016 = data2016_bin["name"]

X_feature2016_scaler = StandardScaler().fit(feature2016)
X_feature2016_scaled = X_feature2016_scaler.transform(feature2016)

predictions2016 = grid.predict(X_feature2016_scaled)
print('Test Acc: %.3f' % grid.score(X_feature2016_scaled, team2016))
predictions2016 = model.predict(X_feature2016_scaled)
print(predictions2016)

Test Acc: 0.167
['Philadelphia Phillies' 'Pittsburgh Pirates' 'Baltimore Orioles'
 'Boston Red Sox' 'New York Mets' 'Minnesota Twins' 'Pittsburgh Pirates'
 'Boston Red Sox' 'Arizona Diamondbacks' 'Detroit Tigers'
 'Oakland Athletics' 'Kansas City Royals' 'Baltimore Orioles'
 'New York Mets' 'San Diego Padres' 'Cincinnati Reds' 'Detroit Tigers'
 'Atlanta Braves' 'Chicago White Sox' 'Chicago White Sox'
 'San Diego Padres' 'Philadelphia Phillies' 'San Diego Padres'
 'Philadelphia Phillies' 'Cleveland Indians' 'Chicago Cubs'
 'Toronto Blue Jays' 'Chicago White Sox' 'Oakland Athletics'
 'Los Angeles Dodgers']

In [82]:
#Read in CSV and create dataframe
mlb_teams2017= pd.read_csv("2017.csv")

mlb2017_df = mlb_teams2017[['yearID', 'lgID', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name']]

data2017_LG = mlb2017_df.copy()
data2017_bin = pd.get_dummies(data2017_LG, columns=["WSWin", "lgID"])
data2017_bin = data2017_bin.drop(columns=['WSWin_N', 'lgID_AL'])

feature2017 = data2017_bin.drop("name", axis=1)
team2017 = data2017_bin["name"]

X_feature2017_scaler = StandardScaler().fit(feature2017)
X_feature2017_scaled = X_feature2017_scaler.transform(feature2017)

predictions2017 = grid.predict(X_feature2017_scaled)
print('Test Acc: %.3f' % grid.score(X_feature2017_scaled, team2017))
predictions2017 = model.predict(X_feature2017_scaled)
print(predictions2017)

Test Acc: 0.100
['Houston Astros' 'Chicago Cubs' 'Baltimore Orioles' 'Baltimore Orioles'
 'Atlanta Braves' 'Kansas City Royals' 'Philadelphia Phillies'
 'Boston Red Sox' 'Pittsburgh Pirates' 'Kansas City Royals'
 'Anaheim Angels' 'Kansas City Royals' 'Oakland Athletics' 'New York Mets'
 'St. Louis Cardinals' 'Cincinnati Reds' 'Boston Red Sox' 'Chicago Cubs'
 'Detroit Tigers' 'Boston Red Sox' 'Pittsburgh Pirates'
 'San Francisco Giants' 'San Diego Padres' 'Pittsburgh Pirates'
 'Seattle Mariners' 'St. Louis Cardinals' 'Chicago White Sox'
 'Oakland Athletics' 'Baltimore Orioles' 'Pittsburgh Pirates']

In [83]:
#Read in CSV and create dataframe
mlb_teams2018= pd.read_csv("2018.csv")

mlb2018_df = mlb_teams2018[['yearID', 'lgID', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name']]

data2018_LG = mlb2018_df.copy()
data2018_bin = pd.get_dummies(data2018_LG, columns=["WSWin", "lgID"])
data2018_bin = data2018_bin.drop(columns=['WSWin_N', 'lgID_AL'])

feature2018 = data2018_bin.drop("name", axis=1)
team2018 = data2018_bin["name"]

X_feature2018_scaler = StandardScaler().fit(feature2018)
X_feature2018_scaled = X_feature2018_scaler.transform(feature2018)

predictions2018 = grid.predict(X_feature2018_scaled)
print('Test Acc: %.3f' % grid.score(X_feature2018_scaled, team2018))
predictions2018 = model.predict(X_feature2018_scaled)
print(predictions2018)

Test Acc: 0.133
['Arizona Diamondbacks' 'St. Louis Cardinals' 'Baltimore Orioles'
 'Toronto Blue Jays' 'Los Angeles Dodgers' 'Detroit Tigers'
 'San Diego Padres' 'Baltimore Orioles' 'Pittsburgh Pirates'
 'Kansas City Royals' 'Baltimore Orioles' 'Kansas City Royals'
 'Chicago White Sox' 'San Francisco Giants' 'San Diego Padres'
 'Los Angeles Dodgers' 'Boston Red Sox' 'Philadelphia Phillies'
 'Oakland Athletics' 'Boston Red Sox' 'San Diego Padres'
 'St. Louis Cardinals' 'San Diego Padres' 'San Diego Padres'
 'Chicago White Sox' 'Atlanta Braves' 'Kansas City Royals'
 'Cleveland Indians' 'Toronto Blue Jays' 'New York Mets']

In [85]:
#Read in CSV and create dataframe
mlb2019_teams= pd.read_csv("MLB 2019 season.csv")

mlb2019_df = mlb2019_teams[['yearID', 'lgID', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name']]

data2019_LG = mlb2019_df.copy()
data2019_bin = pd.get_dummies(data2019_LG, columns=["WSWin", "lgID"])
data2019_bin = data2019_bin.drop(columns=['WSWin_N', 'lgID_AL'])

feature2019 = data2019_bin.drop("name", axis=1)
team2019 = data2019_bin["name"]

X_feature2019_scaler = StandardScaler().fit(feature2019)
X_feature2019_scaled = X_feature2019_scaler.transform(feature2019)

predictions2019 = grid.predict(X_feature2019_scaled)
print('Test Acc: %.3f' % grid.score(X_feature2019_scaled, team2019))
predictions2019 = model.predict(X_feature2019_scaled)
print(predictions2019)

Test Acc: 0.133
['Houston Astros' 'Atlanta Braves' 'Tampa Bay Devil Rays' 'Boston Red Sox'
 'Minnesota Twins' 'Atlanta Braves' 'Atlanta Braves' 'Baltimore Orioles'
 'Colorado Rockies' 'Kansas City Royals' 'New York Yankees'
 'Kansas City Royals' 'Cleveland Indians' 'Atlanta Braves'
 'Philadelphia Phillies' 'Cincinnati Reds' 'Boston Red Sox'
 'Baltimore Orioles' 'Atlanta Braves' 'New York Yankees'
 'Philadelphia Phillies' 'Pittsburgh Pirates' 'San Diego Padres'
 'Detroit Tigers' 'Philadelphia Phillies' 'Los Angeles Dodgers'
 'Minnesota Twins' 'Milwaukee Brewers' 'Detroit Tigers'
 'St. Louis Cardinals']

Evaluate Model

Predict World Series Champs

In [62]:
#Predict outcome
# Calculate classification report
from sklearn.metrics import classification_report
predictions = model.predict(X_feature_scaled)
print(predictions)

['Houston Astros' 'Los Angeles Dodgers' 'Kansas City Royals'
 'Boston Red Sox' 'Minnesota Twins' 'Atlanta Braves' 'Los Angeles Dodgers'
 'Baltimore Orioles' 'Colorado Rockies' 'Kansas City Royals'
 'New York Yankees' 'Kansas City Royals' 'Cleveland Indians'
 'Los Angeles Dodgers' 'Chicago Cubs' 'Cincinnati Reds' 'Boston Red Sox'
 'New York Yankees' 'Atlanta Braves' 'New York Yankees'
 'Philadelphia Phillies' 'Pittsburgh Pirates' 'San Diego Padres'
 'Oakland Athletics' 'Philadelphia Phillies' 'Los Angeles Dodgers'
 'Kansas City Royals' 'Texas Rangers' 'Oakland Athletics'
 'St. Louis Cardinals']

In [63]:
print('Test Acc: %.3f' % grid.score(X_feature_scaled, team))

Test Acc: 0.200

In [39]:
import joblib
filename = 'SWilliams_SVM.sav'
joblib.dump(model, filename)

['SWilliams_SVM.sav']