In [22]:
#import numpy to use seed 
import numpy as np
import pandas as pd
from numpy.random import seed
np.random.seed(1)

In [23]:
#import other dependencies

import os
import tensorflow 
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense

Read CSV create, and clean dataframe

In [24]:
#Read in CSV and create dataframe
mlb_teams= pd.read_csv("Teams.csv")

mlb_teams

,yearID,lgID,G,G.1,W,L,WSWin,R,AB,H,...,3B,HR,BB,SO,SB,ERA,CG,SHO,SV,name
0,1969,NL,162,81,93,69,N,691,5460,1411,...,22,141,485,665,59,3.53,38,7,42,Atlanta Braves
1,1969,AL,162,81,109,53,N,779,5518,1465,...,29,175,634,806,82,2.83,50,20,36,Baltimore Orioles
2,1969,AL,162,81,87,75,N,743,5494,1381,...,37,197,658,923,41,3.92,30,7,41,Boston Red Sox
3,1969,AL,163,81,71,91,N,528,5316,1221,...,29,88,516,929,54,3.54,25,9,39,California Angels
4,1969,AL,162,81,68,94,N,625,5450,1346,...,27,112,552,844,54,4.21,29,10,25,Chicago White Sox
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,2019,NL,162,81,91,71,N,764,5449,1336,...,24,210,561,1420,116,3.80,1,14,52,St. Louis Cardinals
1404,2019,AL,162,81,96,66,N,769,5628,1427,...,29,217,542,1493,94,3.65,0,12,46,Tampa Bay Rays
1405,2019,AL,162,81,78,84,N,810,5540,1374,...,24,223,534,1578,131,5.06,4,9,33,Texas Rangers
1406,2019,AL,162,81,67,95,N,726,5493,1299,...,21,247,509,1514,51,4.79,1,7,33,Toronto Blue Jays
1407,2019,NL,162,81,93,69,Y,873,5512,1460,...,27,231,584,1308,116,4.27,1,13,40,Washington Nationals

In [25]:
#Get list of dataframe columns

mlb_teams.columns

Index(['yearID', 'lgID', 'G', 'G.1', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name'],
      dtype='object')

In [26]:
#Select columns for dataframe

mlb_df = mlb_teams[['yearID', 'lgID', 'G', 'G.1', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV']]
mlb_df.head(20)

,yearID,lgID,G,G.1,W,L,WSWin,R,AB,H,2B,3B,HR,BB,SO,SB,ERA,CG,SHO,SV
0,1969,NL,162,81,93,69,N,691,5460,1411,195,22,141,485,665,59,3.53,38,7,42
1,1969,AL,162,81,109,53,N,779,5518,1465,234,29,175,634,806,82,2.83,50,20,36
2,1969,AL,162,81,87,75,N,743,5494,1381,234,37,197,658,923,41,3.92,30,7,41
3,1969,AL,163,81,71,91,N,528,5316,1221,151,29,88,516,929,54,3.54,25,9,39
4,1969,AL,162,81,68,94,N,625,5450,1346,210,27,112,552,844,54,4.21,29,10,25
5,1969,NL,163,82,92,70,N,720,5530,1400,215,40,142,559,928,30,3.34,58,22,27
6,1969,NL,163,81,89,73,N,798,5634,1558,224,42,171,474,1042,79,4.11,23,11,44
7,1969,AL,161,81,62,99,N,573,5365,1272,173,24,119,535,906,85,3.94,35,7,22
8,1969,AL,162,81,90,72,N,701,5441,1316,188,29,182,578,922,35,3.31,55,20,28
9,1969,NL,162,81,81,81,N,676,5348,1284,208,40,104,699,972,101,3.60,52,11,34
10,1969,AL,163,82,69,93,N,586,5462,1311,179,32,98,522,901,129,3.72,42,10,25
11,1969,NL,162,81,85,77,N,645,5532,1405,185,52,97,484,823,80,3.08,47,20,31
12,1969,AL,162,81,97,65,N,790,5677,1520,246,32,163,599,906,115,3.24,41,8,43
13,1969,NL,162,81,52,110,N,582,5419,1300,202,33,125,529,962,52,4.33,26,8,21
14,1969,AL,162,80,80,81,N,562,5308,1247,210,44,94,565,840,119,3.23,53,13,20
15,1969,NL,162,82,100,62,Y,632,5427,1311,184,41,109,527,1089,66,2.99,51,28,35
16,1969,AL,162,81,88,74,N,740,5614,1400,210,28,148,617,953,100,3.71,42,14,36
17,1969,NL,162,81,63,99,N,645,5408,1304,227,35,137,549,1130,73,4.14,47,14,21
18,1969,NL,162,81,88,74,N,725,5626,1557,220,52,119,454,944,74,3.61,39,9,33
19,1969,NL,162,81,52,110,N,468,5357,1203,180,42,99,423,1143,45,4.24,16,9,25

In [27]:
#Use getdummies to convert strings

data_LG = mlb_df.copy()
data_bin = pd.get_dummies(data_LG, columns=["WSWin"])
data_bin = data_bin.drop(columns=['WSWin_N'])

data_bin.head()

,yearID,lgID,G,G.1,W,L,R,AB,H,2B,3B,HR,BB,SO,SB,ERA,CG,SHO,SV,WSWin_Y
0,1969,NL,162,81,93,69,691,5460,1411,195,22,141,485,665,59,3.53,38,7,42,0
1,1969,AL,162,81,109,53,779,5518,1465,234,29,175,634,806,82,2.83,50,20,36,0
2,1969,AL,162,81,87,75,743,5494,1381,234,37,197,658,923,41,3.92,30,7,41,0
3,1969,AL,163,81,71,91,528,5316,1221,151,29,88,516,929,54,3.54,25,9,39,0
4,1969,AL,162,81,68,94,625,5450,1346,210,27,112,552,844,54,4.21,29,10,25,0

In [28]:
data = data_bin.drop("lgID", axis = 1)
outcome = data_bin["lgID"]
print(data.shape, outcome.shape)

(1408, 19) (1408,)

Preprocess data

In [29]:
#Import SciKit libraries

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from tensorflow.keras.utils import to_categorical

In [30]:
#Split data and teams into training and test data

X_train, X_test, y_train, y_test = train_test_split(data, outcome, random_state=1)
y_train

1114    NL
572     NL
154     AL
575     NL
693     AL
        ..
715     AL
905     NL
1096    NL
235     AL
1061    AL
Name: lgID, Length: 1056, dtype: object

In [31]:
#Scale data using MinMaxScaler

X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_train_scaled

array([[ 1.01159397,  0.2431805 ,  0.24149987, ..., -0.12783391,
         0.56478947, -0.19055211],
       [-0.28813845,  0.1410737 ,  0.44073727, ...,  0.35601058,
         0.13008271, -0.19055211],
       [-1.38264996,  0.2431805 ,  0.24149987, ...,  0.35601058,
        -1.39139098, -0.19055211],
       ...,
       [ 0.943187  ,  0.2431805 ,  0.24149987, ...,  0.59793283,
         0.13008271, -0.19055211],
       [-1.17742905,  0.2431805 ,  0.04226248, ...,  0.35601058,
        -0.95668421, -0.19055211],
       [ 0.87478004,  0.2431805 ,  0.24149987, ...,  0.11408833,
         3.06435338, -0.19055211]])

In [32]:
#Import and use SVC MODEL
from sklearn.svm import SVC 
model = SVC(kernel='linear')
model.fit(X_train_scaled, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [33]:
#Print training and test scores from model using datasets

print(f"Training Data Score: {model.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {model.score(X_test_scaled, y_test)}")

Training Data Score: 0.7376893939393939
Testing Data Score: 0.7301136363636364

In [34]:
# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [100, 500, 1000],
              'gamma': [0.0001, 0.005, 0.001]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [35]:
# Train the model with GridSearch

grid.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] C=100, gamma=0.0001 .............................................

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] ................. C=100, gamma=0.0001, score=0.726, total=   2.3s
[CV] C=100, gamma=0.0001 .............................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.2s remaining:    0.0s

[CV] ................. C=100, gamma=0.0001, score=0.725, total=   1.5s
[CV] C=100, gamma=0.0001 .............................................

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    3.6s remaining:    0.0s

[CV] ................. C=100, gamma=0.0001, score=0.711, total=   1.4s
[CV] C=100, gamma=0.0001 .............................................
[CV] ................. C=100, gamma=0.0001, score=0.725, total=   1.3s
[CV] C=100, gamma=0.0001 .............................................
[CV] ................. C=100, gamma=0.0001, score=0.777, total=   2.2s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.726, total=   2.3s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.725, total=   1.4s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.711, total=   1.3s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.725, total=   1.3s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.777, total=   1.7s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.726, total=   1.9s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.725, total=   1.4s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.711, total=   1.4s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.725, total=   1.2s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.777, total=   1.7s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.726, total=   8.5s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.725, total=   8.0s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.706, total=   8.0s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.720, total=   9.7s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.773, total=  11.6s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.726, total=   9.1s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.725, total=   7.8s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.706, total=   7.8s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.720, total=   9.6s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.773, total=   9.7s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.726, total=   8.5s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.725, total=   9.3s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.706, total=   9.6s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.720, total=  13.7s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.773, total=  12.5s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.726, total=  16.2s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.725, total=  15.9s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.706, total=  13.8s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.720, total=  19.9s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.768, total=  18.7s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.726, total=  14.7s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.725, total=  15.5s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.706, total=  13.5s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.720, total=  19.9s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.768, total=  21.4s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.726, total=  14.2s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.725, total=  16.2s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.706, total=  14.3s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.720, total=  23.5s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.768, total=  20.2s

[Parallel(n_jobs=1)]: Done  45 out of  45 | elapsed:  7.1min finished

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [100, 500, 1000],
                         'gamma': [0.0001, 0.005, 0.001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

Train Model

In [36]:
#Print best parameters and score from Gridsearch

print(grid.best_params_)
print(grid.best_score_)

{'C': 100, 'gamma': 0.0001}
0.732960743986408

In [37]:
#Print accuracy of model using test dataset

print('Test Acc: %.3f' % grid.score(X_test_scaled, y_test))

Test Acc: 0.730

Evaluate Model

Predict World Series Champs

In [38]:
#Predict outcome
# Calculate classification report
from sklearn.metrics import classification_report
predictions = model.predict(X_test_scaled)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

          AL       0.74      0.68      0.71       170
          NL       0.72      0.77      0.75       182

    accuracy                           0.73       352
   macro avg       0.73      0.73      0.73       352
weighted avg       0.73      0.73      0.73       352

In [39]:
import joblib
filename = 'SWilliams_SVM.sav'
joblib.dump(model, filename)

['SWilliams_SVM.sav']