In [1]:
#import numpy to use seed 
import numpy as np
import pandas as pd
from numpy.random import seed
np.random.seed(1)

In [2]:
#import other dependencies

import os
import tensorflow 
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense

Read CSV create, and clean dataframe

In [3]:
#Read in CSV and create dataframe
mlb_teams= pd.read_csv("Team Statistics.csv")

mlb_teams

,YR,LG,Name,G,W,L,WSWin,Unnamed: 7,R,H,2B,3B,HR,BB,Unnamed: 14,SO,ERA,SHO,SV,FP
0,1969,NL,Atlanta Braves,162,93,69,N,NaN,691,1411,195,22,141,485,NaN,665,3.53,7,42,0.981
1,1969,AL,Baltimore Orioles,162,109,53,N,NaN,779,1465,234,29,175,634,NaN,806,2.83,20,36,0.984
2,1969,AL,Boston Red Sox,162,87,75,N,NaN,743,1381,234,37,197,658,NaN,923,3.92,7,41,0.975
3,1969,AL,California Angels,163,71,91,N,NaN,528,1221,151,29,88,516,NaN,929,3.54,9,39,0.978
4,1969,AL,Chicago White Sox,162,68,94,N,NaN,625,1346,210,27,112,552,NaN,844,4.21,10,25,0.981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,2019,NL,St. Louis Cardinals,162,91,71,N,NaN,764,1336,246,24,210,561,NaN,1420,3.80,14,52,0.989
1404,2019,AL,Tampa Bay Rays,162,96,66,N,NaN,769,1427,291,29,217,542,NaN,1493,3.65,12,46,0.985
1405,2019,AL,Texas Rangers,162,78,84,N,NaN,810,1374,296,24,223,534,NaN,1578,5.06,9,33,0.982
1406,2019,AL,Toronto Blue Jays,162,67,95,N,NaN,726,1299,270,21,247,509,NaN,1514,4.79,7,33,0.984
1407,2019,NL,Washington Nationals,162,93,69,Y,NaN,873,1460,298,27,231,584,NaN,1308,4.27,13,40,0.985

In [4]:
#Get list of dataframe columns

mlb_teams.columns

Index(['YR', 'LG', 'Name', 'G', 'W', 'L', 'WSWin', 'Unnamed: 7', 'R', 'H',
       '2B', '3B', 'HR', 'BB', 'Unnamed: 14', 'SO', 'ERA', 'SHO', 'SV', 'FP'],
      dtype='object')

In [5]:
#Select columns for dataframe

mlb_df = mlb_teams[['YR', 'LG', 'Name', 'G', 'W', 'L', 'WSWin', 'R', 'H',
                   '2B', '3B', 'HR', 'BB', 'SO', 'ERA', 'SHO', 'SV', 'FP']]
mlb_df.head(20)

,YR,LG,Name,G,W,L,WSWin,R,H,2B,3B,HR,BB,SO,ERA,SHO,SV,FP
0,1969,NL,Atlanta Braves,162,93,69,N,691,1411,195,22,141,485,665,3.53,7,42,0.981
1,1969,AL,Baltimore Orioles,162,109,53,N,779,1465,234,29,175,634,806,2.83,20,36,0.984
2,1969,AL,Boston Red Sox,162,87,75,N,743,1381,234,37,197,658,923,3.92,7,41,0.975
3,1969,AL,California Angels,163,71,91,N,528,1221,151,29,88,516,929,3.54,9,39,0.978
4,1969,AL,Chicago White Sox,162,68,94,N,625,1346,210,27,112,552,844,4.21,10,25,0.981
5,1969,NL,Chicago Cubs,163,92,70,N,720,1400,215,40,142,559,928,3.34,22,27,0.979
6,1969,NL,Cincinnati Reds,163,89,73,N,798,1558,224,42,171,474,1042,4.11,11,44,0.973
7,1969,AL,Cleveland Indians,161,62,99,N,573,1272,173,24,119,535,906,3.94,7,22,0.976
8,1969,AL,Detroit Tigers,162,90,72,N,701,1316,188,29,182,578,922,3.31,20,28,0.979
9,1969,NL,Houston Astros,162,81,81,N,676,1284,208,40,104,699,972,3.60,11,34,0.975
10,1969,AL,Kansas City Royals,163,69,93,N,586,1311,179,32,98,522,901,3.72,10,25,0.975
11,1969,NL,Los Angeles Dodgers,162,85,77,N,645,1405,185,52,97,484,823,3.08,20,31,0.981
12,1969,AL,Minnesota Twins,162,97,65,N,790,1520,246,32,163,599,906,3.24,8,43,0.977
13,1969,NL,Montreal Expos,162,52,110,N,582,1300,202,33,125,529,962,4.33,8,21,0.970
14,1969,AL,New York Yankees,162,80,81,N,562,1247,210,44,94,565,840,3.23,13,20,0.979
15,1969,NL,New York Mets,162,100,62,Y,632,1311,184,41,109,527,1089,2.99,28,35,0.980
16,1969,AL,Oakland Athletics,162,88,74,N,740,1400,210,28,148,617,953,3.71,14,36,0.978
17,1969,NL,Philadelphia Phillies,162,63,99,N,645,1304,227,35,137,549,1130,4.14,14,21,0.978
18,1969,NL,Pittsburgh Pirates,162,88,74,N,725,1557,220,52,119,454,944,3.61,9,33,0.975
19,1969,NL,San Diego Padres,162,52,110,N,468,1203,180,42,99,423,1143,4.24,9,25,0.975

In [6]:
#Set X(data) and y(team)variables

data = mlb_df.drop("Name", axis=1)
team = mlb_df["Name"]
print(data.shape, team.shape)

(1408, 17) (1408,)

In [7]:
#Use getdummies to convert strings

data_LG = data.copy()
data_bin = pd.get_dummies(data_LG, columns=["LG", "WSWin"])
data_bin = data_bin.drop(columns=['LG_AL','WSWin_N'])

data_bin.head()

,YR,G,W,L,R,H,2B,3B,HR,BB,SO,ERA,SHO,SV,FP,LG_NL,WSWin_Y
0,1969,162,93,69,691,1411,195,22,141,485,665,3.53,7,42,0.981,1,0
1,1969,162,109,53,779,1465,234,29,175,634,806,2.83,20,36,0.984,0,0
2,1969,162,87,75,743,1381,234,37,197,658,923,3.92,7,41,0.975,0,0
3,1969,163,71,91,528,1221,151,29,88,516,929,3.54,9,39,0.978,0,0
4,1969,162,68,94,625,1346,210,27,112,552,844,4.21,10,25,0.981,0,0

Preprocess data

In [8]:
#Import SciKit libraries

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical

In [9]:
#Split data and teams into training and test data

X_train, X_test, y_train, y_test = train_test_split(data_bin, team, random_state=1)
y_train

1114                  Cincinnati Reds
572                     New York Mets
154                Kansas City Royals
575                Pittsburgh Pirates
693                 Baltimore Orioles
                    ...
715                  Seattle Mariners
905                   Cincinnati Reds
1096                    New York Mets
235                 Oakland Athletics
1061    Los Angeles Angels of Anaheim
Name: Name, Length: 1056, dtype: object

In [10]:
#Scale data using MinMaxScaler

X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_train_scaled

array([[0.82      , 0.96721311, 0.66666667, ..., 0.86956522, 1.        ,
        0.        ],
       [0.44      , 0.95081967, 0.48      , ..., 0.39130435, 1.        ,
        0.        ],
       [0.12      , 0.96721311, 0.66666667, ..., 0.34782609, 0.        ,
        0.        ],
       ...,
       [0.8       , 0.96721311, 0.38666667, ..., 0.69565217, 1.        ,
        0.        ],
       [0.18      , 0.96721311, 0.37333333, ..., 0.13043478, 0.        ,
        0.        ],
       [0.78      , 0.96721311, 0.78666667, ..., 0.73913043, 0.        ,
        0.        ]])

In [11]:
##Import RandomForestClassifier and train

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train_scaled, y_train)

In [12]:
#Get Score for RandomForestClassifier

rf.score(X_test_scaled, y_test)

0.24431818181818182

Create Neural Network Model

In [13]:
#Print data scores for training aand test datasets
print(f"Training Data Score: {rf.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {rf.score(X_test_scaled, y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.24431818181818182

In [16]:
from sklearn.model_selection import GridSearchCV

param_grid = {"bootstrap": [True],
              "max_depth": [80, 90, 100, 125],
#              "max_features": [2,3],
 #            "min_samples_leaf": [3, 4, 5],
              "n_estimators": [100, 500, 1000]
              }
grid = GridSearchCV(rf, param_grid, verbose=3)
grid

GridSearchCV(cv=None, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=200, n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'bootstrap': [True], 'max_depth': [80, 90, 100, 125],
                         'n_estimators': [100, 500, 1000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

Train Model

In [17]:
# Train the model with GridSearch

grid.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] bootstrap=True, max_depth=80, n_estimators=100 ..................

C:\Users\swill\Anaconda3\envs\PythonData\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV]  bootstrap=True, max_depth=80, n_estimators=100, score=0.274, total=   0.3s
[CV] bootstrap=True, max_depth=80, n_estimators=100 ..................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s

[CV]  bootstrap=True, max_depth=80, n_estimators=100, score=0.246, total=   0.3s
[CV] bootstrap=True, max_depth=80, n_estimators=100 ..................

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.6s remaining:    0.0s

[CV]  bootstrap=True, max_depth=80, n_estimators=100, score=0.275, total=   0.3s
[CV] bootstrap=True, max_depth=80, n_estimators=100 ..................
[CV]  bootstrap=True, max_depth=80, n_estimators=100, score=0.156, total=   0.3s
[CV] bootstrap=True, max_depth=80, n_estimators=100 ..................
[CV]  bootstrap=True, max_depth=80, n_estimators=100, score=0.232, total=   0.3s
[CV] bootstrap=True, max_depth=80, n_estimators=500 ..................
[CV]  bootstrap=True, max_depth=80, n_estimators=500, score=0.278, total=   1.6s
[CV] bootstrap=True, max_depth=80, n_estimators=500 ..................
[CV]  bootstrap=True, max_depth=80, n_estimators=500, score=0.289, total=   1.7s
[CV] bootstrap=True, max_depth=80, n_estimators=500 ..................
[CV]  bootstrap=True, max_depth=80, n_estimators=500, score=0.261, total=   1.6s
[CV] bootstrap=True, max_depth=80, n_estimators=500 ..................
[CV]  bootstrap=True, max_depth=80, n_estimators=500, score=0.204, total=   1.6s
[CV] bootstrap=True, max_depth=80, n_estimators=500 ..................
[CV]  bootstrap=True, max_depth=80, n_estimators=500, score=0.204, total=   1.6s
[CV] bootstrap=True, max_depth=80, n_estimators=1000 .................
[CV]  bootstrap=True, max_depth=80, n_estimators=1000, score=0.264, total=   3.3s
[CV] bootstrap=True, max_depth=80, n_estimators=1000 .................
[CV]  bootstrap=True, max_depth=80, n_estimators=1000, score=0.280, total=   3.3s
[CV] bootstrap=True, max_depth=80, n_estimators=1000 .................
[CV]  bootstrap=True, max_depth=80, n_estimators=1000, score=0.270, total=   3.3s
[CV] bootstrap=True, max_depth=80, n_estimators=1000 .................
[CV]  bootstrap=True, max_depth=80, n_estimators=1000, score=0.194, total=   3.3s
[CV] bootstrap=True, max_depth=80, n_estimators=1000 .................
[CV]  bootstrap=True, max_depth=80, n_estimators=1000, score=0.213, total=   3.4s
[CV] bootstrap=True, max_depth=90, n_estimators=100 ..................
[CV]  bootstrap=True, max_depth=90, n_estimators=100, score=0.264, total=   0.3s
[CV] bootstrap=True, max_depth=90, n_estimators=100 ..................
[CV]  bootstrap=True, max_depth=90, n_estimators=100, score=0.261, total=   0.3s
[CV] bootstrap=True, max_depth=90, n_estimators=100 ..................
[CV]  bootstrap=True, max_depth=90, n_estimators=100, score=0.261, total=   0.3s
[CV] bootstrap=True, max_depth=90, n_estimators=100 ..................
[CV]  bootstrap=True, max_depth=90, n_estimators=100, score=0.171, total=   0.3s
[CV] bootstrap=True, max_depth=90, n_estimators=100 ..................
[CV]  bootstrap=True, max_depth=90, n_estimators=100, score=0.223, total=   0.3s
[CV] bootstrap=True, max_depth=90, n_estimators=500 ..................
[CV]  bootstrap=True, max_depth=90, n_estimators=500, score=0.269, total=   1.6s
[CV] bootstrap=True, max_depth=90, n_estimators=500 ..................
[CV]  bootstrap=True, max_depth=90, n_estimators=500, score=0.270, total=   1.6s
[CV] bootstrap=True, max_depth=90, n_estimators=500 ..................
[CV]  bootstrap=True, max_depth=90, n_estimators=500, score=0.265, total=   1.6s
[CV] bootstrap=True, max_depth=90, n_estimators=500 ..................
[CV]  bootstrap=True, max_depth=90, n_estimators=500, score=0.180, total=   1.6s
[CV] bootstrap=True, max_depth=90, n_estimators=500 ..................
[CV]  bootstrap=True, max_depth=90, n_estimators=500, score=0.237, total=   1.6s
[CV] bootstrap=True, max_depth=90, n_estimators=1000 .................
[CV]  bootstrap=True, max_depth=90, n_estimators=1000, score=0.264, total=   3.2s
[CV] bootstrap=True, max_depth=90, n_estimators=1000 .................
[CV]  bootstrap=True, max_depth=90, n_estimators=1000, score=0.280, total=   3.3s
[CV] bootstrap=True, max_depth=90, n_estimators=1000 .................
[CV]  bootstrap=True, max_depth=90, n_estimators=1000, score=0.289, total=   3.3s
[CV] bootstrap=True, max_depth=90, n_estimators=1000 .................
[CV]  bootstrap=True, max_depth=90, n_estimators=1000, score=0.166, total=   3.3s
[CV] bootstrap=True, max_depth=90, n_estimators=1000 .................
[CV]  bootstrap=True, max_depth=90, n_estimators=1000, score=0.223, total=   3.3s
[CV] bootstrap=True, max_depth=100, n_estimators=100 .................
[CV]  bootstrap=True, max_depth=100, n_estimators=100, score=0.236, total=   0.4s
[CV] bootstrap=True, max_depth=100, n_estimators=100 .................
[CV]  bootstrap=True, max_depth=100, n_estimators=100, score=0.265, total=   0.3s
[CV] bootstrap=True, max_depth=100, n_estimators=100 .................
[CV]  bootstrap=True, max_depth=100, n_estimators=100, score=0.284, total=   0.4s
[CV] bootstrap=True, max_depth=100, n_estimators=100 .................
[CV]  bootstrap=True, max_depth=100, n_estimators=100, score=0.194, total=   0.3s
[CV] bootstrap=True, max_depth=100, n_estimators=100 .................
[CV]  bootstrap=True, max_depth=100, n_estimators=100, score=0.204, total=   0.4s
[CV] bootstrap=True, max_depth=100, n_estimators=500 .................
[CV]  bootstrap=True, max_depth=100, n_estimators=500, score=0.250, total=   1.8s
[CV] bootstrap=True, max_depth=100, n_estimators=500 .................
[CV]  bootstrap=True, max_depth=100, n_estimators=500, score=0.265, total=   1.8s
[CV] bootstrap=True, max_depth=100, n_estimators=500 .................
[CV]  bootstrap=True, max_depth=100, n_estimators=500, score=0.261, total=   1.7s
[CV] bootstrap=True, max_depth=100, n_estimators=500 .................
[CV]  bootstrap=True, max_depth=100, n_estimators=500, score=0.180, total=   1.7s
[CV] bootstrap=True, max_depth=100, n_estimators=500 .................
[CV]  bootstrap=True, max_depth=100, n_estimators=500, score=0.227, total=   1.7s
[CV] bootstrap=True, max_depth=100, n_estimators=1000 ................
[CV]  bootstrap=True, max_depth=100, n_estimators=1000, score=0.283, total=   3.3s
[CV] bootstrap=True, max_depth=100, n_estimators=1000 ................
[CV]  bootstrap=True, max_depth=100, n_estimators=1000, score=0.280, total=   3.3s
[CV] bootstrap=True, max_depth=100, n_estimators=1000 ................
[CV]  bootstrap=True, max_depth=100, n_estimators=1000, score=0.303, total=   3.3s
[CV] bootstrap=True, max_depth=100, n_estimators=1000 ................
[CV]  bootstrap=True, max_depth=100, n_estimators=1000, score=0.199, total=   3.3s
[CV] bootstrap=True, max_depth=100, n_estimators=1000 ................
[CV]  bootstrap=True, max_depth=100, n_estimators=1000, score=0.237, total=   3.3s
[CV] bootstrap=True, max_depth=125, n_estimators=100 .................
[CV]  bootstrap=True, max_depth=125, n_estimators=100, score=0.259, total=   0.3s
[CV] bootstrap=True, max_depth=125, n_estimators=100 .................
[CV]  bootstrap=True, max_depth=125, n_estimators=100, score=0.237, total=   0.3s
[CV] bootstrap=True, max_depth=125, n_estimators=100 .................
[CV]  bootstrap=True, max_depth=125, n_estimators=100, score=0.265, total=   0.3s
[CV] bootstrap=True, max_depth=125, n_estimators=100 .................
[CV]  bootstrap=True, max_depth=125, n_estimators=100, score=0.156, total=   0.3s
[CV] bootstrap=True, max_depth=125, n_estimators=100 .................
[CV]  bootstrap=True, max_depth=125, n_estimators=100, score=0.218, total=   0.3s
[CV] bootstrap=True, max_depth=125, n_estimators=500 .................
[CV]  bootstrap=True, max_depth=125, n_estimators=500, score=0.264, total=   1.7s
[CV] bootstrap=True, max_depth=125, n_estimators=500 .................
[CV]  bootstrap=True, max_depth=125, n_estimators=500, score=0.280, total=   1.7s
[CV] bootstrap=True, max_depth=125, n_estimators=500 .................
[CV]  bootstrap=True, max_depth=125, n_estimators=500, score=0.251, total=   1.6s
[CV] bootstrap=True, max_depth=125, n_estimators=500 .................
[CV]  bootstrap=True, max_depth=125, n_estimators=500, score=0.171, total=   1.6s
[CV] bootstrap=True, max_depth=125, n_estimators=500 .................
[CV]  bootstrap=True, max_depth=125, n_estimators=500, score=0.227, total=   1.6s
[CV] bootstrap=True, max_depth=125, n_estimators=1000 ................
[CV]  bootstrap=True, max_depth=125, n_estimators=1000, score=0.255, total=   3.5s
[CV] bootstrap=True, max_depth=125, n_estimators=1000 ................

[CV]  bootstrap=True, max_depth=125, n_estimators=1000, score=0.299, total=   3.3s
[CV] bootstrap=True, max_depth=125, n_estimators=1000 ................
[CV]  bootstrap=True, max_depth=125, n_estimators=1000, score=0.280, total=   3.3s
[CV] bootstrap=True, max_depth=125, n_estimators=1000 ................
[CV]  bootstrap=True, max_depth=125, n_estimators=1000, score=0.156, total=   3.3s
[CV] bootstrap=True, max_depth=125, n_estimators=1000 ................
[CV]  bootstrap=True, max_depth=125, n_estimators=1000, score=0.232, total=   3.3s

[Parallel(n_jobs=1)]: Done  60 out of  60 | elapsed:  1.8min finished

GridSearchCV(cv=None, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=200, n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'bootstrap': [True], 'max_depth': [80, 90, 100, 125],
                         'n_estimators': [100, 500, 1000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [16]:
#Print best parameter and score 

print(grid.best_params_)
print(grid.best_score_)

{'bootstrap': True, 'max_depth': 80, 'n_estimators': 500}
0.2528346597514084

Evaluate Model

In [17]:
#Make prediction using test data

predictions = grid.predict(X_test_scaled)

Predict World Series Champs

In [18]:
##Print accuracy score for test data

print('Test Acc: %.3f' % grid.score(X_test_scaled, y_test))

Test Acc: 0.224