In [45]:
#import numpy to use seed 
import numpy as np
import pandas as pd
from numpy.random import seed
np.random.seed(1)

In [46]:
#import other dependencies

import os
import tensorflow 
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense

Read CSV create, and clean dataframe

In [47]:
#Read in CSV and create dataframe
mlb_teams= pd.read_csv("Teams.csv")

mlb_teams

,yearID,lgID,G,G.1,W,L,WSWin,R,AB,H,...,3B,HR,BB,SO,SB,ERA,CG,SHO,SV,name
0,1997,AL,162,82,84,78,N,829,5628,1531,...,25,161,617,953,126,4.52,9,5,39,Anaheim Angels
1,1998,AL,162,81,85,77,N,787,5630,1530,...,27,147,510,1028,93,4.49,3,5,52,Anaheim Angels
2,1999,AL,162,81,70,92,N,711,5494,1404,...,22,158,511,1022,71,4.79,4,7,37,Anaheim Angels
3,2000,AL,162,81,82,80,N,864,5628,1574,...,34,236,608,1024,93,5.00,5,3,46,Anaheim Angels
4,2001,AL,162,81,75,87,N,691,5551,1447,...,26,158,494,1001,116,4.20,6,1,43,Anaheim Angels
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1373,2017,NL,162,81,97,65,N,819,5553,1477,...,31,215,542,1327,108,3.88,3,5,46,Washington Nationals
1374,2018,NL,162,81,82,80,N,771,5517,1402,...,25,191,631,1289,119,4.04,2,7,40,Washington Nationals
1375,1969,AL,162,81,86,76,N,694,5447,1365,...,40,148,630,900,52,3.49,28,10,41,Washington Senators
1376,1970,AL,162,81,70,92,N,626,5460,1302,...,28,138,635,989,72,3.80,20,11,40,Washington Senators
1377,1971,AL,159,81,63,96,N,537,5290,1219,...,30,86,575,956,68,3.70,30,10,26,Washington Senators

In [48]:
#Get list of dataframe columns

mlb_teams.columns

Index(['yearID', 'lgID', 'G', 'G.1', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name'],
      dtype='object')

In [49]:
#Select columns for dataframe

mlb_df = mlb_teams[['yearID', 'lgID', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name']]
mlb_df.head(20)

,yearID,lgID,W,L,WSWin,R,AB,H,2B,3B,HR,BB,SO,SB,ERA,CG,SHO,SV,name
0,1997,AL,84,78,N,829,5628,1531,279,25,161,617,953,126,4.52,9,5,39,Anaheim Angels
1,1998,AL,85,77,N,787,5630,1530,314,27,147,510,1028,93,4.49,3,5,52,Anaheim Angels
2,1999,AL,70,92,N,711,5494,1404,248,22,158,511,1022,71,4.79,4,7,37,Anaheim Angels
3,2000,AL,82,80,N,864,5628,1574,309,34,236,608,1024,93,5.00,5,3,46,Anaheim Angels
4,2001,AL,75,87,N,691,5551,1447,275,26,158,494,1001,116,4.20,6,1,43,Anaheim Angels
5,2002,AL,99,63,Y,851,5678,1603,333,32,152,462,805,117,3.69,7,14,54,Anaheim Angels
6,2003,AL,77,85,N,736,5487,1473,276,33,150,476,838,129,4.28,5,9,39,Anaheim Angels
7,2004,AL,92,70,N,836,5675,1603,272,37,162,450,942,143,4.28,2,11,50,Anaheim Angels
8,1998,NL,65,97,N,665,5491,1353,235,46,159,489,1239,73,4.63,7,6,37,Arizona Diamondbacks
9,1999,NL,100,62,N,908,5658,1566,289,46,216,588,1045,137,3.77,16,9,42,Arizona Diamondbacks
10,2000,NL,85,77,N,792,5527,1466,282,44,179,535,975,97,4.35,16,8,38,Arizona Diamondbacks
11,2001,NL,92,70,Y,818,5595,1494,284,35,208,587,1052,71,3.87,12,13,34,Arizona Diamondbacks
12,2002,NL,98,64,N,819,5508,1471,283,41,165,643,1016,92,3.92,14,10,40,Arizona Diamondbacks
13,2003,NL,84,78,N,717,5570,1467,303,47,152,531,1006,76,3.84,7,11,42,Arizona Diamondbacks
14,2004,NL,51,111,N,615,5544,1401,295,38,135,441,1022,53,4.98,5,6,33,Arizona Diamondbacks
15,2005,NL,77,85,N,696,5550,1419,291,27,191,606,1094,67,4.84,6,10,45,Arizona Diamondbacks
16,2006,NL,76,86,N,773,5645,1506,331,38,160,504,965,76,4.48,8,9,34,Arizona Diamondbacks
17,2007,NL,90,72,N,712,5398,1350,286,40,171,532,1111,109,4.13,7,12,51,Arizona Diamondbacks
18,2008,NL,82,80,N,720,5409,1355,318,47,159,587,1287,58,3.98,6,9,39,Arizona Diamondbacks
19,2009,NL,70,92,N,720,5565,1408,307,45,173,571,1298,102,4.42,4,12,36,Arizona Diamondbacks

In [50]:
#Use getdummies to convert strings

data_LG = mlb_df.copy()
data_bin = pd.get_dummies(data_LG, columns=["WSWin", "lgID"])
data_bin = data_bin.drop(columns=['WSWin_N', 'lgID_AL'])

data_bin.head()

,yearID,W,L,R,AB,H,2B,3B,HR,BB,SO,SB,ERA,CG,SHO,SV,name,WSWin_Y,lgID_NL
0,1997,84,78,829,5628,1531,279,25,161,617,953,126,4.52,9,5,39,Anaheim Angels,0,0
1,1998,85,77,787,5630,1530,314,27,147,510,1028,93,4.49,3,5,52,Anaheim Angels,0,0
2,1999,70,92,711,5494,1404,248,22,158,511,1022,71,4.79,4,7,37,Anaheim Angels,0,0
3,2000,82,80,864,5628,1574,309,34,236,608,1024,93,5.00,5,3,46,Anaheim Angels,0,0
4,2001,75,87,691,5551,1447,275,26,158,494,1001,116,4.20,6,1,43,Anaheim Angels,0,0

In [51]:
data = data_bin.drop("name", axis = 1)
outcome = data_bin["name"]
print(data.shape, outcome.shape)

(1378, 18) (1378,)

Preprocess data

In [52]:
#Import SciKit libraries

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from tensorflow.keras.utils import to_categorical

In [53]:
#Split data and teams into training and test data

X_train, X_test, y_train, y_test = train_test_split(data, outcome, random_state=1)
y_train

41         Atlanta Braves
785        Montreal Expos
99      Baltimore Orioles
414      Colorado Rockies
709     Milwaukee Brewers
              ...
715     Milwaukee Brewers
905      New York Yankees
1096     San Diego Padres
235          Chicago Cubs
1061     San Diego Padres
Name: name, Length: 1033, dtype: object

In [54]:
#Scale data using MinMaxScaler

X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
X_train_scaled

array([[-0.92679464, -2.41685621, -1.93735924, ..., -1.46413069,
        -0.19273971,  0.99710004],
       [-0.85757486,  0.5373263 , -0.30218309, ...,  0.60279681,
        -0.19273971,  0.99710004],
       [-0.37303635,  0.61938693, -0.38394189, ...,  0.71158247,
        -0.19273971, -1.00290839],
       ...,
       [ 0.87291981,  0.78350818, -0.4657007 , ...,  0.82036813,
        -0.19273971,  0.99710004],
       [ 0.18072194, -0.93976496,  1.16947545, ..., -0.04991714,
        -0.19273971,  0.99710004],
       [-1.54977272, -1.76037121,  1.25123426, ..., -2.00805898,
        -0.19273971,  0.99710004]])

In [55]:
#Import and use SVC MODEL
from sklearn.svm import SVC 
model = SVC(kernel='linear')
model.fit(X_train_scaled, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [56]:
#Print training and test scores from model using datasets

print(f"Training Data Score: {model.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {model.score(X_test_scaled, y_test)}")

Training Data Score: 0.462729912875121
Testing Data Score: 0.24057971014492754

In [57]:
# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [100, 500, 1000],
              'gamma': [0.0001, 0.005, 0.001]}
grid = GridSearchCV(model, param_grid, verbose=3)

In [58]:
# Train the model with GridSearch

grid.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] C=100, gamma=0.0001 .............................................

C:\Users\swill\Anaconda3\envs\PythonData\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  % (min_groups, self.n_splits)), UserWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV] ................. C=100, gamma=0.0001, score=0.237, total=   3.1s
[CV] C=100, gamma=0.0001 .............................................

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.0s remaining:    0.0s

[CV] ................. C=100, gamma=0.0001, score=0.242, total=   3.3s
[CV] C=100, gamma=0.0001 .............................................

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    6.3s remaining:    0.0s

[CV] ................. C=100, gamma=0.0001, score=0.222, total=   3.3s
[CV] C=100, gamma=0.0001 .............................................
[CV] ................. C=100, gamma=0.0001, score=0.228, total=   2.6s
[CV] C=100, gamma=0.0001 .............................................
[CV] ................. C=100, gamma=0.0001, score=0.233, total=   3.3s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.237, total=   2.9s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.242, total=   3.3s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.222, total=   3.4s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.228, total=   2.5s
[CV] C=100, gamma=0.005 ..............................................
[CV] .................. C=100, gamma=0.005, score=0.233, total=   3.2s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.237, total=   2.8s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.242, total=   3.2s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.222, total=   3.2s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.228, total=   2.4s
[CV] C=100, gamma=0.001 ..............................................
[CV] .................. C=100, gamma=0.001, score=0.233, total=   3.4s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.232, total=  11.3s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.237, total=  15.3s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.217, total=  11.0s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.218, total=  10.5s
[CV] C=500, gamma=0.0001 .............................................
[CV] ................. C=500, gamma=0.0001, score=0.218, total=  11.2s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.232, total=   9.8s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.237, total=  13.9s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.217, total=  11.0s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.218, total=  12.4s
[CV] C=500, gamma=0.005 ..............................................
[CV] .................. C=500, gamma=0.005, score=0.218, total=  14.1s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.232, total=   9.6s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.237, total=  19.7s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.217, total=  12.4s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.218, total=  11.0s
[CV] C=500, gamma=0.001 ..............................................
[CV] .................. C=500, gamma=0.001, score=0.218, total=  11.2s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.222, total=  23.5s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.242, total=  28.8s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.222, total=  26.9s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.218, total=  24.4s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................ C=1000, gamma=0.0001, score=0.228, total=  25.8s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.222, total=  22.8s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.242, total=  27.2s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.222, total=  23.1s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.218, total=  24.8s
[CV] C=1000, gamma=0.005 .............................................
[CV] ................. C=1000, gamma=0.005, score=0.228, total=  25.9s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.222, total=  20.0s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.242, total=  27.6s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.222, total=  21.9s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.218, total=  20.9s
[CV] C=1000, gamma=0.001 .............................................
[CV] ................. C=1000, gamma=0.001, score=0.228, total=  30.4s

[Parallel(n_jobs=1)]: Done  45 out of  45 | elapsed: 10.1min finished

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [100, 500, 1000],
                         'gamma': [0.0001, 0.005, 0.001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

Train Model

In [59]:
#Print best parameters and score from Gridsearch

print(grid.best_params_)
print(grid.best_score_)

{'C': 100, 'gamma': 0.0001}
0.23232962806622579

In [60]:
#Print accuracy of model using test dataset

print('Test Acc: %.3f' % grid.score(X_test_scaled, y_test))

Test Acc: 0.229

In [ ]:
#Read in CSV and create dataframe
mlb_teams2015= pd.read_csv("2015.csv")

mlb2015_df = mlb_teams2015[['yearID', 'lgID', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name']]

data2015_LG = mlb2015_df.copy()
data2015_bin = pd.get_dummies(data2015_LG, columns=["WSWin", "lgID"])
data2015_bin = data2015_bin.drop(columns=['WSWin_N', 'lgID_AL'])

feature2015 = data2015_bin.drop("name", axis=1)
team2015 = data2015_bin["name"]

X_feature2015_scaler = StandardScaler().fit(feature2015)
X_feature2015_scaled = X_feature2015_scaler.transform(feature2015)

predictions2015 = grid.predict(X_feature2015_scaled)
print('Test Acc: %.3f' % grid.score(X_feature2015_scaled, team2015))
predictions2015 = model.predict(X_feature2015_scaled)
print(predictions2015)

In [ ]:
#Read in CSV and create dataframe
mlb_teams2016= pd.read_csv("2016.csv")

mlb2016_df = mlb_teams2016[['yearID', 'lgID', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name']]

data2016_LG = mlb2016_df.copy()
data2016_bin = pd.get_dummies(data2016_LG, columns=["WSWin", "lgID"])
data2016_bin = data2016_bin.drop(columns=['WSWin_N', 'lgID_AL'])

feature2016 = data2016_bin.drop("name", axis=1)
team2016 = data2016_bin["name"]

X_feature2016_scaler = StandardScaler().fit(feature2016)
X_feature2016_scaled = X_feature2016_scaler.transform(feature2016)

predictions2016 = grid.predict(X_feature2016_scaled)
print('Test Acc: %.3f' % grid.score(X_feature2016_scaled, team2016))
predictions2016 = model.predict(X_feature2016_scaled)
print(predictions2016)

In [ ]:
#Read in CSV and create dataframe
mlb_teams2017= pd.read_csv("2017.csv")

mlb2017_df = mlb_teams2017[['yearID', 'lgID', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name']]

data2017_LG = mlb2017_df.copy()
data2017_bin = pd.get_dummies(data2017_LG, columns=["WSWin", "lgID"])
data2017_bin = data2017_bin.drop(columns=['WSWin_N', 'lgID_AL'])

feature2017 = data2017_bin.drop("name", axis=1)
team2017 = data2017_bin["name"]

X_feature2017_scaler = StandardScaler().fit(feature2017)
X_feature2017_scaled = X_feature2017_scaler.transform(feature2017)

predictions2017 = grid.predict(X_feature2017_scaled)
print('Test Acc: %.3f' % grid.score(X_feature2017_scaled, team2017))
predictions2017 = model.predict(X_feature2017_scaled)
print(predictions2017)

In [ ]:
#Read in CSV and create dataframe
mlb_teams2018= pd.read_csv("2018.csv")

mlb2018_df = mlb_teams2018[['yearID', 'lgID', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name']]

data2018_LG = mlb2018_df.copy()
data2018_bin = pd.get_dummies(data2018_LG, columns=["WSWin", "lgID"])
data2018_bin = data2018_bin.drop(columns=['WSWin_N', 'lgID_AL'])

feature2018 = data2018_bin.drop("name", axis=1)
team2018 = data2018_bin["name"]

X_feature2018_scaler = StandardScaler().fit(feature2018)
X_feature2018_scaled = X_feature2018_scaler.transform(feature2018)

predictions2018 = grid.predict(X_feature2018_scaled)
print('Test Acc: %.3f' % grid.score(X_feature2018_scaled, team2018))
predictions2018 = model.predict(X_feature2018_scaled)
print(predictions2018)

In [61]:
#Read in CSV and create dataframe
mlb2019_teams= pd.read_csv("MLB 2019 season.csv")

mlb2019_df = mlb2019_teams[['yearID', 'lgID', 'W', 'L', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'ERA', 'CG', 'SHO', 'SV', 'name']]

data2019_LG = mlb2019_df.copy()
data2019_bin = pd.get_dummies(data2019_LG, columns=["WSWin", "lgID"])
data2019_bin = data2019_bin.drop(columns=['WSWin_N', 'lgID_AL'])

feature2019 = data2019_bin.drop("name", axis=1)
team2019 = data2019_bin["name"]

X_feature2019_scaler = StandardScaler().fit(feature2019)
X_feature2019_scaled = X_feature2019_scaler.transform(feature2019)

predictions2019 = grid.predict(X_feature2019_scaled)
print('Test Acc: %.3f' % grid.score(X_feature2019_scaled, team2019))
predictions2019 = rf.predict(X_feature2019_scaled)
print(predictions2019)

Evaluate Model

Predict World Series Champs

In [62]:
#Predict outcome
# Calculate classification report
from sklearn.metrics import classification_report
predictions = model.predict(X_feature_scaled)
print(predictions)

['Houston Astros' 'Los Angeles Dodgers' 'Kansas City Royals'
 'Boston Red Sox' 'Minnesota Twins' 'Atlanta Braves' 'Los Angeles Dodgers'
 'Baltimore Orioles' 'Colorado Rockies' 'Kansas City Royals'
 'New York Yankees' 'Kansas City Royals' 'Cleveland Indians'
 'Los Angeles Dodgers' 'Chicago Cubs' 'Cincinnati Reds' 'Boston Red Sox'
 'New York Yankees' 'Atlanta Braves' 'New York Yankees'
 'Philadelphia Phillies' 'Pittsburgh Pirates' 'San Diego Padres'
 'Oakland Athletics' 'Philadelphia Phillies' 'Los Angeles Dodgers'
 'Kansas City Royals' 'Texas Rangers' 'Oakland Athletics'
 'St. Louis Cardinals']

In [63]:
print('Test Acc: %.3f' % grid.score(X_feature_scaled, team))

Test Acc: 0.200

In [39]:
import joblib
filename = 'SWilliams_SVM.sav'
joblib.dump(model, filename)

['SWilliams_SVM.sav']